version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./payment/pgdata:/var/lib/postgresql/data