version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./payment/pgdata:/var/lib/postgresql/data

  payment-server:
    image: popokola/payment-api:latest
    ports:
      - "${BACK_PORT:-3000}:${BACK_PORT:-3000}" 
    container_name: node-api

  vue-ui:
    image: popokola/payment-front:latest
    ports:
      - "${FRONT_PORT:-80}:${FRONT_PORT:-80}"  # Use 80 as default if FRONT_PORT is not set
    container_name: vuejs-front

  merchant-ui:
    image: popokola/merchant-front:latest 
    ports:
      - "${MERCHANT_PORT:-9393}:${MERCHANT_PORT:-9393}" 
    container_name: vuejs-merchant
