version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./payment/pgdata:/var/lib/postgresql/data
  nodejs-server:
    build:
      context: ./payment/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
      - ./payment/api:/usr/src/app/payment/api
      - /usr/src/app/payment/api/node_modules
    depends_on:
      - postgres
  vue-ui:
    build:
      context: ./payment/front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vuejs-front
    volumes:
      - ./payment/front:/usr/src/app/payment/front
      - /usr/src/app/payment/front/node_modules