version: '3'
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  vue-ui:
    build:
      context: ./front
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: vuejs-front
    volumes:
      - ./front:/usr/src/app/front
      # - /usr/src/app/front/node_modules