name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: payment/api

      - name: Display checked-out directory
        run: |
          echo "Checked-out directory: $PWD"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Change directory to /payment/api
        run: cd payment/api

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
